# 📰 어린이 뉴스 데이터 요약패턴 개발

## 1. data import

In [92]:
# 설정초기화
pd.reset_option('display')

In [90]:
pd.options.display.max_rows = 6

In [1]:
# row 생략 없이 출력
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_rows', 10)

In [2]:
import pandas as pd
import numpy as np
from tabulate import tabulate

In [3]:
news_summary = pd.read_csv('./kid_news.csv', index_col=[0])

In [4]:
news_summary.head()

news_title          news_subtitle  \
0                [세상 속으로] "러시아 고양이는 안 됩니다"  국제고양이연맹, '월드 캣 쇼'서 퇴출   
1  [뉴스탐험대] 홀로 1000㎞… 우크라 國境<국경> 탈출한 11세 소년                    NaN   
2         [뉴스탐험대] 온라인 쇼핑몰 '니켈·납투성이 장신구' 주의                    NaN   
3      [뉴스탐험대] "코로나에 강한 혈액형 있다"… O형, 위험 최저                    NaN   
4              잡히지 않는 火魔<화마>… 문화재 등 대규모 피해      서울 면적 4분의 1 이상 불타   

                                        news_article  \
0  전 세계가 우크라이나를 침공(侵攻)한 러시아에 각종 제재를 가하고 있다. 이에 러시...   
1  우크라이나 소년이 홀로 국경(國境)을 넘은 뭉클한 연이 전해졌다. 영국 매체 가디언...   
2  온라인 쇼핑몰에서 '무(無)알러지' '무니켈 도금' 등으로 홍보·판매되는 액세서리에...   
3  혈액형이 O형(型)인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보...   
4  최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림(山林) 피해가 우려되고 있...   

                                            news_url  
0  http://kid.chosun.com/site/data/html_dir/2022/...  
1  http://kid.chosun.com/site/data/html_dir/2022/...  
2  http://kid.chosun.com/site/data/html_dir/2022/...  
3  http://kid.chosun.com/site/data/html_dir/2022/...  
4  http://kid.chosun.com/site/data/html_dir/2022/...

In [5]:
news_summary.iloc[:, :3]

news_title          news_subtitle  \
0                   [세상 속으로] "러시아 고양이는 안 됩니다"  국제고양이연맹, '월드 캣 쇼'서 퇴출   
1     [뉴스탐험대] 홀로 1000㎞… 우크라 國境<국경> 탈출한 11세 소년                    NaN   
2            [뉴스탐험대] 온라인 쇼핑몰 '니켈·납투성이 장신구' 주의                    NaN   
3         [뉴스탐험대] "코로나에 강한 혈액형 있다"… O형, 위험 최저                    NaN   
4                 잡히지 않는 火魔<화마>… 문화재 등 대규모 피해      서울 면적 4분의 1 이상 불타   
...                                       ...                    ...   
1670      돼지 뇌에 컴퓨터 칩 연결… 생각만으로 기계 움직일 수 있을까?                    NaN   
1671               탑승형 로봇 '프로스테시스' 조종사를 뽑습니다!                    NaN   
1672                모험 떠날 준비 됐니? 그럼, 책장을 펼쳐봐!                    NaN   
1673                 방탄소년단·블랙핑크, 세계 음원시장 '올킬'                    NaN   
1674             알파고가 이세돌 9단을 이긴 건 '딥러닝' 덕분이지                    NaN   

                                           news_article  
0     전 세계가 우크라이나를 침공(侵攻)한 러시아에 각종 제재를 가하고 있다. 이에 러시...  
1     우크라이나 소년이 홀로 국경(國境)을 넘은 뭉클한 연이 전해졌다. 영국 매체 가디언...  
2     온라인 쇼핑몰에서 '무(無)알러지' '무니켈 도금' 등으로 홍보·판매되는 액세서리에...  
3     혈액형이 O형(型)인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보...  
4     최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림(山林) 피해가 우려되고 있...  
...                                                 ...  
1670  머스크, 유튜브에 실험 돼지 '거트루드' 공개 "뇌 질환 치료 도움… 올해 안에 람...  
1671  람의 팔다리에 연결해 조종 "로봇 활용한 경주 스포츠 만들 것" 람이 탑승한 로봇끼...  
1672  띵똥! 선물이 도착했습니다. 판타지 소설 '해리포터'의 작가 조앤 롤링(55·영국)...  
1673  아이돌 그룹 방탄소년단(BTS)과 블랙핑크가 세계 무대를 뒤흔들고 있다. 글로벌 시...  
1674  '인공 지능 의'가 있는 병원을 상상한 적 있니? 놀랍게도 벌써 우리나라 한 병원에...  

[1675 rows x 3 columns]

In [6]:
pd.set_option('display.width', 10)

In [7]:
news_summary.columns

Index(['news_title',
       'news_subtitle',
       'news_article',
       'news_url'],
      dtype='object')

---

## 2. 데이터 전처리(Data Preprocessing)

### 결측치 확인

In [8]:
news_summary.shape

(1675, 4)

In [9]:
news_summary.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1675 entries, 0 to 1674
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   news_title     1675 non-null   object
 1   news_subtitle  403 non-null    object
 2   news_article   1636 non-null   object
 3   news_url       1675 non-null   object
dtypes: object(4)
memory usage: 65.4+ KB


In [10]:
news_summary.isnull()

news_title  \
0          False   
1          False   
2          False   
3          False   
4          False   
...          ...   
1670       False   
1671       False   
1672       False   
1673       False   
1674       False   

      news_subtitle  \
0             False   
1              True   
2              True   
3              True   
4             False   
...             ...   
1670           True   
1671           True   
1672           True   
1673           True   
1674           True   

      news_article  \
0            False   
1            False   
2            False   
3            False   
4            False   
...            ...   
1670         False   
1671         False   
1672         False   
1673         False   
1674         False   

      news_url  
0        False  
1        False  
2        False  
3        False  
4        False  
...        ...  
1670     False  
1671     False  
1672     False  
1673     False  
1674     False  

[1675 rows x 4 columns]

In [11]:
news_summary.isnull().sum()

news_title          0
news_subtitle    1272
news_article       39
news_url            0
dtype: int64

In [12]:
# null/NaN to ""
news_summary = news_summary.fillna("")
# dropna
# news_summary = news_summary.dropna(subset=['news_article'])

In [13]:
news_summary.shape

(1675, 4)

In [14]:
# null
news_summary.isnull().sum()

news_title       0
news_subtitle    0
news_article     0
news_url         0
dtype: int64

In [15]:
# NaN
news_summary.isna().sum()

news_title       0
news_subtitle    0
news_article     0
news_url         0
dtype: int64

---

### 문자열 길이 확인 및 추가

In [16]:
news_summary.dtypes

news_title       object
news_subtitle    object
news_article     object
news_url         object
dtype: object

In [17]:
# 문자열 길이
news_summary.news_article.str.len()

0        469
1        380
2        446
3        451
4        620
        ... 
1670    1124
1671     721
1672    1668
1673     756
1674    1717
Name: news_article, Length: 1675, dtype: int64

In [18]:
news_summary["news_len"] = news_summary.news_article.str.len()

In [19]:
news_summary[news_summary.news_len.isnull()][:2]

Empty DataFrame
Columns: [news_title, news_subtitle, news_article, news_url, news_len]
Index: []

In [20]:
# NaN
news_summary.isna().sum()

news_title       0
news_subtitle    0
news_article     0
news_url         0
news_len         0
dtype: int64

In [21]:
# null/NaN to 0
news_summary = news_summary.fillna(0)

In [22]:
# IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer 
news_summary['news_len'] = news_summary['news_len'].astype(int)

In [23]:
news_summary.head()

news_title  \
0                [세상 속으로] "러시아 고양이는 안 됩니다"   
1  [뉴스탐험대] 홀로 1000㎞… 우크라 國境<국경> 탈출한 11세 소년   
2         [뉴스탐험대] 온라인 쇼핑몰 '니켈·납투성이 장신구' 주의   
3      [뉴스탐험대] "코로나에 강한 혈액형 있다"… O형, 위험 최저   
4              잡히지 않는 火魔<화마>… 문화재 등 대규모 피해   

           news_subtitle  \
0  국제고양이연맹, '월드 캣 쇼'서 퇴출   
1                          
2                          
3                          
4      서울 면적 4분의 1 이상 불타   

                                        news_article  \
0  전 세계가 우크라이나를 침공(侵攻)한 러시아에 각종 제재를 가하고 있다. 이에 러시...   
1  우크라이나 소년이 홀로 국경(國境)을 넘은 뭉클한 연이 전해졌다. 영국 매체 가디언...   
2  온라인 쇼핑몰에서 '무(無)알러지' '무니켈 도금' 등으로 홍보·판매되는 액세서리에...   
3  혈액형이 O형(型)인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보...   
4  최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림(山林) 피해가 우려되고 있...   

                                            news_url  \
0  http://kid.chosun.com/site/data/html_dir/2022/...   
1  http://kid.chosun.com/site/data/html_dir/2022/...   
2  http://kid.chosun.com/site/data/html_dir/2022/...   
3  http://kid.chosun.com/site/data/html_dir/2022/...   
4  http://kid.chosun.com/site/data/html_dir/2022/...   

   news_len  
0       469  
1       380  
2       446  
3       451  
4       620

---

### 이상치 확인
- 이상한 뉴스 데이터 확인

In [24]:
pd.set_option('display.max_rows', None)

In [25]:
# 기사 길이 작은거 검색
condition = (news_summary.news_len <= 200)
# = news_summary.loc[condition]
shorts_news_summary = news_summary[condition][['news_title','news_url','news_len']].sort_values(by='news_len' ,ascending=True)
shorts_news_summary

news_title  \
8                                   [메시지 뉴스] 명태·대게와 러시아   
303                                     [메시지 뉴스] 동지(冬至)   
325                                  [메시지 뉴스] 성탄 트리의 기원   
389                                   [메시지 뉴스] 일본 한류 열풍   
400                                    [메시지 뉴스] 우주탐사 인형   
423                                  [메시지 뉴스] 대학수학 능력시험   
451                                      [메시지 뉴스] COP26   
485                                [메시지 뉴스] 기초 학력과 학교생활   
504                                     [메시지 뉴스] 대통령 선거   
536                                       [메시지 뉴스] 탄소중립   
568                                         [메시지 뉴스] 골프   
586                                       [메시지 뉴스] 국정감사   
612                                       [메시지 뉴스] 기네스북   
644                                         [메시지 뉴스] 추석   
671                                     [메시지 뉴스] 아프간 전쟁   
697                                     [메시지 뉴스] 코로나 백신   
1383                   [요리 쿡! 조리 쿡!] 시원하고 달콤하고 코코아 아이스바   
1409                [요리 쿡! 조리 쿡!] 호호 불어 드세요 돌돌 말린 채소 춘권   
1413             [요리 쿡! 조리 쿡!] 콕콕 찍어 입으로 쏙쏙 톡톡 튀는 팝콘 치킨   
1438              [요리 쿡! 조리 쿡!] 파티 음식으로도 'OK' 토마토 브루스케타   
275                                  [메시지 뉴스] 세계의 새해 풍습   
244                                  [메시지 뉴스] 성년(成年) 기준   
1654                                            기자들의 수다   
205                       [영상-맛있는 실험실] 감자채 피자를 만들어 봤어요‼   
37                                          [메시지 뉴스] 체스   
69                                  [메시지 뉴스] 용감하게 질문하기!   
214                                   [메시지 뉴스] 어린이 교통안전   
108                   [꿀beetv] 안철수 후보의 '어린이를 위한 대선공약'은?   
109              [꿀beetv] 어린이조선일보 기자들의 해보GO! "별걸 다 꾸며요"   
111                                [메시지 뉴스] 한국판 미네르바 大學   
120                        [꿀BEE] 강아지 건강에 최고인 수제 간식 만들기   
125             [신자영의 5분 영어] 모니 모니 석가모니 일화 속 영어 표현 배우기!   
126                    [일상 속 간단한 운동] 본지 기자들, 스트레칭에 도전하다   
92                                     [메시지 뉴스] 올바른 양치법   
164                               [메시지 뉴스] 어린이 안전 관리 강화   
203                      [영상-출동! 명예기자] 국립과학수사연구원을 체험하다!   
144            [영상-출동! 명예기자] 화제의 인물 글 쓰는 의사 '남궁인'을 만나다!   
187                              [메시지 뉴스] 재밌는 지하철역명 이야기   
202            [영상-출동! 명예기자] 새벽배송 쇼핑몰 '마켓컬리' 김슬아 대표 인터뷰   
706                         [생생~~영상뉴스] 머리에 밥솥 달린 로봇 이야기   
368               [생생 인터뷰 현장!] 주한 프랑스 대사 '필립 르포르'를 만나다!   
691                            [생생~~영상뉴스] 환경파괴의 주범 누텔라?   
717                        잠자리 드론과 풍선 망원경? 과감한 박새의 사연은?   
825   [동영상]"니네 집에 요리로봇 있어? 비서로봇은?"..."로봇 몇 대 있니?" 묻는...   
289                            [정답 공개] 크리스마스 퍼즐, 숨은그림찾기   
76                      [꿀BeeTV] 출동! 명예기자 충주 기상과학관에 가다!   
147                                         신자영의 5분 영어!   
590                       [POPCORN NEWS] 국군의 날 특집! 영상뉴스   
1501                          간편하게 한 끼 챙길 땐 쫀득쫀득 그래놀라 바   
1498                              편하게 들고 '쏙쏙' 한입 토스트 꼬치   
1525                               노릇하게 구워볼까? 폭신폭신 팬케이크   
352                               [메시지 뉴스] 세상 가장 작은 나라들   
1569                    [카드뉴스] "취미활동 늘었지만, 친구 못만나 속상해요"   
1444                                  돌돌 말렸네! 맛있는 시금치 롤   
70                           [꿀BeeTV] '알리와 아브라함' 형제 이야기   
15                      [꿀BeeTV] 무인도에서 극적으로 탈출한 생존자 이야기   
93                      [꿀beetv] 대나무와 고사리 그리고 한 남자의 이야기   
1464                                  초콜릿 잼 품은 바나나 크레이프   
47                      [꿀BeeTV] 아무리 돈이 많아도 살 수 없는 것은?    
1575                              기록, 또 기록… 케이팝에 한계란 없다   

                                               news_url  \
8     http://kid.chosun.com/site/data/html_dir/2022/...   
303   http://kid.chosun.com/site/data/html_dir/2021/...   
325   http://kid.chosun.com/site/data/html_dir/2021/...   
389   http://kid.chosun.com/site/data/html_dir/2021/...   
400   http://kid.chosun.com/site/data/html_dir/2021/...   
423   http://kid.chosun.com/site/data/html_dir/2021/...   
451   http://kid.chosun.com/site

In [26]:
shorts_news_summary.shape

(60, 3)

In [27]:
type(shorts_news_summary.news_url)

pandas.core.series.Series

In [28]:
# url 전체 출력
# shorts_news_url = shorts_news_summary.news_url
# for url in shorts_news_url:
#     print(url)

In [29]:
# [메세지 뉴스]에 내용 없음
shorts_news_url = shorts_news_summary.news_url.values[0]
shorts_news_url

'http://kid.chosun.com/site/data/html_dir/2022/03/07/2022030702124.html'

In [30]:
# [꿀beetv] 
shorts_news_summary.loc[[93]].news_url.values[0]

'http://kid.chosun.com/site/data/html_dir/2022/02/12/2022021201006.html'

In [31]:
# 기록, 또 기록… 케이팝에 한계란 없다 ?
shorts_news_summary.loc[shorts_news_summary.index == 1575].news_url.values[0]

'http://kid.chosun.com/site/data/html_dir/2020/10/13/2020101301951.html'

In [32]:
type(shorts_news_url)

str

---

### 데이터 삭제

In [33]:
shorts_news_title = shorts_news_summary.news_title
shorts_news_title.head()

8      [메시지 뉴스] 명태·대게와 러시아
303        [메시지 뉴스] 동지(冬至)
325     [메시지 뉴스] 성탄 트리의 기원
389      [메시지 뉴스] 일본 한류 열풍
400       [메시지 뉴스] 우주탐사 인형
Name: news_title, dtype: object

In [34]:
# title [] 안에 text 확인
import re
result_title = []
for title in shorts_news_title:
    # m = re.match(r'\[[^)]*\]', title)
    # m = re.match(r'(\[)(.*?)(\])', title)
    m = re.search(r'(?<=\[).*(?=\])', title)
    if m :
        result_title.append(m.group())
    else:
        sub_text = re.sub(r'[?]',"\?",title)
        result_title.append(sub_text)

In [35]:
title_set = set(result_title)
[key for key in title_set]

['카드뉴스',
 '일상 속 간단한 운동',
 '영상-맛있는 실험실',
 '동영상',
 '간편하게 한 끼 챙길 땐 쫀득쫀득 그래놀라 바',
 "편하게 들고 '쏙쏙' 한입 토스트 꼬치",
 '신자영의 5분 영어!',
 '신자영의 5분 영어',
 '메시지 뉴스',
 '생생~~영상뉴스',
 'POPCORN NEWS',
 '생생 인터뷰 현장!',
 '기자들의 수다',
 '초콜릿 잼 품은 바나나 크레이프',
 '영상-출동! 명예기자',
 '꿀BeeTV',
 '꿀beetv',
 '꿀BEE',
 '요리 쿡! 조리 쿡!',
 '기록, 또 기록… 케이팝에 한계란 없다',
 '노릇하게 구워볼까\\? 폭신폭신 팬케이크',
 '정답 공개',
 '잠자리 드론과 풍선 망원경\\? 과감한 박새의 사연은\\?',
 '돌돌 말렸네! 맛있는 시금치 롤']

In [36]:
# news_summary[~news_summary['news_title'].str.contains(i)]
for i in title_set:
    condition = news_summary[news_summary['news_title'].str.contains(i)].index
    news_summary.drop(condition,inplace=True)

In [37]:
# title에 '영상' 들어간 거 확인
news_summary[news_summary['news_title'].str.contains(r'(\[)(.*영상.*)(\])')]

/var/folders/m6/hrff0b7x4hl1m5j8nxchlk5c0000gn/T/ipykernel_39367/1892139044.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  news_summary[news_summary['news_title'].str.contains(r'(\[)(.*영상.*)(\])')]


Empty DataFrame
Columns: [news_title, news_subtitle, news_article, news_url, news_len]
Index: []

In [38]:
news_summary.news_title.unique()

array(['[세상 속으로] "러시아 고양이는 안 됩니다"',
       '[뉴스탐험대] 홀로 1000㎞… 우크라 國境<국경> 탈출한 11세 소년',
       "[뉴스탐험대] 온라인 쇼핑몰 '니켈·납투성이 장신구' 주의", ...,
       '모험 떠날 준비 됐니? 그럼, 책장을 펼쳐봐!', "방탄소년단·블랙핑크, 세계 음원시장 '올킬'",
       "알파고가 이세돌 9단을 이긴 건 '딥러닝' 덕분이지"], dtype=object)

In [39]:
#str.extract()사용 할수도 있음

In [40]:
# 인덱스 재정렬
news_summary.reset_index(drop=True,inplace=True)

In [41]:
# 초기 데이터 : 1675
news_summary.shape

(1538, 5)

In [42]:
# 설정초기화
pd.reset_option('display')

---

### 특수문자 및 공백 제거

**0. Basic**
- 기초적인 전처리,
- html tag 제거(크롤링한 데이터일경우)
- 숫자, 영어, 특수문자 등 필요하지 않은 언어 제거
- Lowercasing
- "@%*=()/+ 와 같은 punctuation(문장부호) 제거
- 한자 - 삭제할지 고민


In [43]:
import re 
def clean_text(texts): 
    corpus = [] 
    for i in range(0, len(texts)): 
        article = re.sub(r'(\[)(.*?)(\])',"",str(texts[i])) #remove [title]
        article = re.sub(r'[@%\\*=()/~#&\+á?\xc3\xa1\-\|\:\;\!\-\,\_\~\$\'\"\→\[\]]', '',article) #remove punctuation 
        # article = re.sub(r'\d+','', str(texts[i]))# remove number 
        # article = review.lower() #lower case 
        article = re.sub(r'\s+', ' ', article) #remove extra space 
        article = re.sub(r'<[^>]+>','',article) #remove Html tags 
        article = re.sub(r'\s+', ' ', article) #remove spaces
        article = re.sub(r"^\s+", '', article) #remove space from start
        article = re.sub(r'\s+$', '', article) #remove space from the end 
        article = re.sub(r'[一-龥]', '', article) #remove Chinese character
        corpus.append(article) 
    return corpus

- news_title 전처리

In [44]:
news_summary["news_title_clean"] = clean_text(news_summary.news_title)

- news_article 전처리

In [45]:
news_summary["news_article_clean"] = clean_text(news_summary.news_article)

In [46]:
news_summary.iloc[:, 4:]

news_len                    news_title_clean  \
0          469                      러시아 고양이는 안 됩니다   
1          380           홀로 1000㎞… 우크라  탈출한 11세 소년   
2          446              온라인 쇼핑몰 니켈·납투성이 장신구 주의   
3          451            코로나에 강한 혈액형 있다… O형 위험 최저   
4          620               잡히지 않는 … 문화재 등 대규모 피해   
...        ...                                 ...   
1533      1124  돼지 뇌에 컴퓨터 칩 연결… 생각만으로 기계 움직일 수 있을까   
1534       721             탑승형 로봇 프로스테시스 조종사를 뽑습니다   
1535      1668              모험 떠날 준비 됐니 그럼 책장을 펼쳐봐   
1536       756               방탄소년단·블랙핑크 세계 음원시장 올킬   
1537      1717          알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지   

                                     news_article_clean  
0     전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다. 이에 러시아 고양...  
1     우크라이나 소년이 홀로 국경을 넘은 뭉클한 연이 전해졌다. 영국 매체 가디언과 메트...  
2     온라인 쇼핑몰에서 무알러지 무니켈 도금 등으로 홍보·판매되는 액세서리에서 기준치를 ...  
3     혈액형이 O형인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보다 낮...  
4     최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림 피해가 우려되고 있다. 지...  
...                                                 ...  
1533  머스크 유튜브에 실험 돼지 거트루드 공개 뇌 질환 치료 도움… 올해 안에 람 적용 ...  
1534  람의 팔다리에 연결해 조종 로봇 활용한 경주 스포츠 만들 것 람이 탑승한 로봇끼리 ...  
1535  띵똥 선물이 도착했습니다. 판타지 소설 해리포터의 작가 조앤 롤링55·영국이 코로나...  
1536  아이돌 그룹 방탄소년단BTS과 블랙핑크가 세계 무대를 뒤흔들고 있다. 글로벌 시장을...  
1537  인공 지능 의가 있는 병원을 상상한 적 있니 놀랍게도 벌써 우리나라 한 병원에서는 ...  

[1538 rows x 3 columns]

---

## 3. news_article 문장 분리

### split() 사용

In [47]:
# (\. ) 온점으로 분리
news_summary["news_article_split"] = news_summary.news_article_clean.str.split('\. ')

In [48]:
# news_summary.news_article_split.str.strip('news_article_split')

In [49]:
news_summary["news_article_split"]

0       [전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다, 이에 러시아 고...
1       [우크라이나 소년이 홀로 국경을 넘은 뭉클한 연이 전해졌다, 영국 매체 가디언과 메...
2       [온라인 쇼핑몰에서 무알러지 무니켈 도금 등으로 홍보·판매되는 액세서리에서 기준치를...
3       [혈액형이 O형인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보다 ...
4       [최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림 피해가 우려되고 있다, ...
                              ...                        
1533    [머스크 유튜브에 실험 돼지 거트루드 공개 뇌 질환 치료 도움… 올해 안에 람 적용...
1534    [람의 팔다리에 연결해 조종 로봇 활용한 경주 스포츠 만들 것 람이 탑승한 로봇끼리...
1535    [띵똥 선물이 도착했습니다, 판타지 소설 해리포터의 작가 조앤 롤링55·영국이 코로...
1536    [아이돌 그룹 방탄소년단BTS과 블랙핑크가 세계 무대를 뒤흔들고 있다, 글로벌 시장...
1537    [인공 지능 의가 있는 병원을 상상한 적 있니 놀랍게도 벌써 우리나라 한 병원에서는...
Name: news_article_split, Length: 1538, dtype: object

In [50]:
news_summary.news_article[0]

'전 세계가 우크라이나를 침공(侵攻)한 러시아에 각종 제재를 가하고 있다. 이에 러시아 고양이도 \'국제 대회\'에 출전하지 못한다는 소식이 전해졌다. 지난 3일(현지 시각), 영국 일간(日刊) 데일리메일에 따르면 70여 년 역(歷史)를 가 국제고양이연맹(FIFE)이 최근 성명을 통해 \'월드 캣 쇼\'에 러시아(社) 소속 고양이 참가를 금지하겠다고 밝혔다. 고양이연맹은 \'예쁜 고양이 대회\'를 비롯해 매년 700여 개의 고양이 관련 대회를 주최해왔다. 연맹 측은 "오는 5월 말까지 러시아산(産) 고양이의 수입을 금지하고, 러시아에서 태어난 고양이의 혈통서 등록도 허용하지 않겠다"며 "우크라이나를 향한 러시아의 잔혹한 행위에 대해 더 이상 침묵할 수 없었다"고 밝혔다. 이어 "우크라이나 난민(難民)과 피란 중인 반려동물을 위한 기금도 마련할 것"이라고 덧붙였다. → 러시아 고양이의 \'국제 대회 출전 금지령(令)\'에 대해 어떻게 생각하나요?'

In [51]:
news_summary["news_article_split"][0]

['전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다',
 '이에 러시아 고양이도 국제 대회에 출전하지 못한다는 소식이 전해졌다',
 '지난 3일현지 시각 영국 일간 데일리메일에 따르면 70여 년 역를 가 국제고양이연맹FIFE이 최근 성명을 통해 월드 캣 쇼에 러시아 소속 고양이 참가를 금지하겠다고 밝혔다',
 '고양이연맹은 예쁜 고양이 대회를 비롯해 매년 700여 개의 고양이 관련 대회를 주최해왔다',
 '연맹 측은 오는 5월 말까지 러시아산 고양이의 수입을 금지하고 러시아에서 태어난 고양이의 혈통서 등록도 허용하지 않겠다며 우크라이나를 향한 러시아의 잔혹한 행위에 대해 더 이상 침묵할 수 없었다고 밝혔다',
 '이어 우크라이나 난민과 피란 중인 반려동물을 위한 기금도 마련할 것이라고 덧붙였다',
 '러시아 고양이의 국제 대회 출전 금지령에 대해 어떻게 생각하나요']

In [52]:
news_summary["news_article_split"][0][0]

'전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다'

In [53]:
news_summary.iloc[:, 4:]

news_len                    news_title_clean  \
0          469                      러시아 고양이는 안 됩니다   
1          380           홀로 1000㎞… 우크라  탈출한 11세 소년   
2          446              온라인 쇼핑몰 니켈·납투성이 장신구 주의   
3          451            코로나에 강한 혈액형 있다… O형 위험 최저   
4          620               잡히지 않는 … 문화재 등 대규모 피해   
...        ...                                 ...   
1533      1124  돼지 뇌에 컴퓨터 칩 연결… 생각만으로 기계 움직일 수 있을까   
1534       721             탑승형 로봇 프로스테시스 조종사를 뽑습니다   
1535      1668              모험 떠날 준비 됐니 그럼 책장을 펼쳐봐   
1536       756               방탄소년단·블랙핑크 세계 음원시장 올킬   
1537      1717          알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지   

                                     news_article_clean  \
0     전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다. 이에 러시아 고양...   
1     우크라이나 소년이 홀로 국경을 넘은 뭉클한 연이 전해졌다. 영국 매체 가디언과 메트...   
2     온라인 쇼핑몰에서 무알러지 무니켈 도금 등으로 홍보·판매되는 액세서리에서 기준치를 ...   
3     혈액형이 O형인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보다 낮...   
4     최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림 피해가 우려되고 있다. 지...   
...                                                 ...   
1533  머스크 유튜브에 실험 돼지 거트루드 공개 뇌 질환 치료 도움… 올해 안에 람 적용 ...   
1534  람의 팔다리에 연결해 조종 로봇 활용한 경주 스포츠 만들 것 람이 탑승한 로봇끼리 ...   
1535  띵똥 선물이 도착했습니다. 판타지 소설 해리포터의 작가 조앤 롤링55·영국이 코로나...   
1536  아이돌 그룹 방탄소년단BTS과 블랙핑크가 세계 무대를 뒤흔들고 있다. 글로벌 시장을...   
1537  인공 지능 의가 있는 병원을 상상한 적 있니 놀랍게도 벌써 우리나라 한 병원에서는 ...   

                                     news_article_split  
0     [전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다, 이에 러시아 고...  
1     [우크라이나 소년이 홀로 국경을 넘은 뭉클한 연이 전해졌다, 영국 매체 가디언과 메...  
2     [온라인 쇼핑몰에서 무알러지 무니켈 도금 등으로 홍보·판매되는 액세서리에서 기준치를...  
3     [혈액형이 O형인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보다 ...  
4     [최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림 피해가 우려되고 있다, ...  
...                                                 ...  
1533  [머스크 유튜브에 실험 돼지 거트루드 공개 뇌 질환 치료 도움… 올해 안에 람 적용...  
1534  [람의 팔다리에 연결해 조종 로봇 활용한 경주 스포츠 만들 것 람이 탑승한 로봇끼리...  
1535  [띵똥 선물이 도착했습니다, 판타지 소설 해리포터의 작가 조앤 롤링55·영국이 코로...  
1536  [아이돌 그룹 방탄소년단BTS과 블랙핑크가 세계 무대를 뒤흔들고 있다, 글로벌 시장...  
1537  [인공 지능 의가 있는 병원을 상상한 적 있니 놀랍게도 벌써 우리나라 한 병원에서는...  

[1538 rows x 4 columns]

### nltk 활용

In [54]:
# Series to list type
#news_list = news_summary.news_article_clean.to_list()

In [55]:
from nltk.tokenize import sent_tokenize
import pprint
pp = pprint.PrettyPrinter(indent=0)

article_text = news_summary["news_article_clean"][0]
# print('문장 토큰화1 :',sent_tokenize(text))
pp.pprint(sent_tokenize(article_text))

['전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다.',
'이에 러시아 고양이도 국제 대회에 출전하지 못한다는 소식이 전해졌다.',
'지난 3일현지 시각 영국 일간 데일리메일에 따르면 70여 년 역를 가 국제고양이연맹FIFE이 최근 성명을 통해 월드 캣 쇼에 러시아 소속 '
'고양이 참가를 금지하겠다고 밝혔다.',
'고양이연맹은 예쁜 고양이 대회를 비롯해 매년 700여 개의 고양이 관련 대회를 주최해왔다.',
'연맹 측은 오는 5월 말까지 러시아산 고양이의 수입을 금지하고 러시아에서 태어난 고양이의 혈통서 등록도 허용하지 않겠다며 우크라이나를 향한 '
'러시아의 잔혹한 행위에 대해 더 이상 침묵할 수 없었다고 밝혔다.',
'이어 우크라이나 난민과 피란 중인 반려동물을 위한 기금도 마련할 것이라고 덧붙였다.',
'러시아 고양이의 국제 대회 출전 금지령에 대해 어떻게 생각하나요']


---

## 4. 전처리 끝난 DataFrame 재생성
- 라벨링 판정 form에 맞춰 DataFrame 재생성

In [56]:
p_news_summary = news_summary[['news_subtitle','news_title_clean','news_article_split']]
p_news_summary

news_subtitle                    news_title_clean  \
0     국제고양이연맹, '월드 캣 쇼'서 퇴출                      러시아 고양이는 안 됩니다   
1                                     홀로 1000㎞… 우크라  탈출한 11세 소년   
2                                        온라인 쇼핑몰 니켈·납투성이 장신구 주의   
3                                      코로나에 강한 혈액형 있다… O형 위험 최저   
4         서울 면적 4분의 1 이상 불타               잡히지 않는 … 문화재 등 대규모 피해   
...                     ...                                 ...   
1533                         돼지 뇌에 컴퓨터 칩 연결… 생각만으로 기계 움직일 수 있을까   
1534                                    탑승형 로봇 프로스테시스 조종사를 뽑습니다   
1535                                     모험 떠날 준비 됐니 그럼 책장을 펼쳐봐   
1536                                      방탄소년단·블랙핑크 세계 음원시장 올킬   
1537                                 알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지   

                                     news_article_split  
0     [전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다, 이에 러시아 고...  
1     [우크라이나 소년이 홀로 국경을 넘은 뭉클한 연이 전해졌다, 영국 매체 가디언과 메...  
2     [온라인 쇼핑몰에서 무알러지 무니켈 도금 등으로 홍보·판매되는 액세서리에서 기준치를...  
3     [혈액형이 O형인 람이 코로나 바이러스 감염 시 망·위중증 위험이 다른 혈액형보다 ...  
4     [최근 발생한 동해안 지역 대규모 산불로 인해 막대한 산림 피해가 우려되고 있다, ...  
...                                                 ...  
1533  [머스크 유튜브에 실험 돼지 거트루드 공개 뇌 질환 치료 도움… 올해 안에 람 적용...  
1534  [람의 팔다리에 연결해 조종 로봇 활용한 경주 스포츠 만들 것 람이 탑승한 로봇끼리...  
1535  [띵똥 선물이 도착했습니다, 판타지 소설 해리포터의 작가 조앤 롤링55·영국이 코로...  
1536  [아이돌 그룹 방탄소년단BTS과 블랙핑크가 세계 무대를 뒤흔들고 있다, 글로벌 시장...  
1537  [인공 지능 의가 있는 병원을 상상한 적 있니 놀랍게도 벌써 우리나라 한 병원에서는...  

[1538 rows x 3 columns]

In [57]:
p_news_summary.shape

(1538, 3)

In [58]:
# zip - news_article + news_title + news_subtitle (1차원 + 1차원 + 2차원 = 2차원 )
def zip_dataframe(index):
    total_data = []  

    new_news_article = p_news_summary.news_article_split[index]
    new_news_title = []
    new_news_subtitle = []
    new_news_index = []

    for i in range(len(new_news_article)):
        new_news_title.append(p_news_summary.news_title_clean[index])
        new_news_subtitle.append(p_news_summary.news_subtitle[index])
        new_news_index.append(index + 1)
    for idx, title, subtitle, article in zip(new_news_index, new_news_title, new_news_subtitle, new_news_article): 
        total_data.append([idx,title,subtitle,article]) 
        
    return total_data

In [59]:
# 전체 dataframe에서 실행
total_data = []
for inxx in p_news_summary.index:
    new_news_article = p_news_summary.news_article_split[inxx]
    new_news_title = []
    new_news_subtitle = []
    new_news_index = []

    for i in range(len(new_news_article)):
        new_news_title.append(p_news_summary.news_title_clean[inxx])
        new_news_subtitle.append(p_news_summary.news_subtitle[inxx])
        new_news_index.append(inxx + 1)
    for idx, title, subtitle, article in zip(new_news_index, new_news_title, new_news_subtitle, new_news_article): 
        total_data.append([idx,title,subtitle,article]) 

In [60]:
new_news_summary = pd.DataFrame(columns = ['news_idx','news_title','news_subtitle','news_article'],data=total_data)
new_news_summary

news_idx                  news_title          news_subtitle  \
0             1              러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
1             1              러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
2             1              러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
3             1              러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
4             1              러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
...         ...                         ...                    ...   
28987      1538  알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지                          
28988      1538  알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지                          
28989      1538  알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지                          
28990      1538  알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지                          
28991      1538  알파고가 이세돌 9단을 이긴 건 딥러닝 덕분이지                          

                                            news_article  
0                    전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다  
1                  이에 러시아 고양이도 국제 대회에 출전하지 못한다는 소식이 전해졌다  
2      지난 3일현지 시각 영국 일간 데일리메일에 따르면 70여 년 역를 가 국제고양이연맹...  
3      고양이연맹은 예쁜 고양이 대회를 비롯해 매년 700여 개의 고양이 관련 대회를 주최해왔다  
4      연맹 측은 오는 5월 말까지 러시아산 고양이의 수입을 금지하고 러시아에서 태어난 고...  
...                                                  ...  
28987         알파고는 이런 훈련을 몇 주 만에 끝내고 이세돌 9단을 이길 수 있었던 거야  
28988  아마도 람이 이 방법으로 학습한다면 똑같은 과정을 거치는 데 1000년도 더 걸렸을...  
28989  우리에게는 너무 당연한 일이지만 예전에는 컴퓨터가 람 얼굴과 고양이 얼굴을 구별하는...  
28990                     알파고처럼 학습한 끝에 고양이를 알아차릴 수 있게 됐지  
28991              다락원 어린이를 위한 4차 산업 혁명 안내서 정윤선 글 우연희 그림  

[28992 rows x 4 columns]

In [61]:
# # pandas.DataFrame.itertuples 각 행에 대한 튜플을 반복하는 객체를 반환
# for index, row in p_news_summary.iterrows():
#     print(index)
#     print('~~~~~~')
    
#     print(row)
#     print('------')

---

## 5. 형태소 분석

POS 비교 : https://docs.google.com/spreadsheets/d/1OGAjUvalBuX-oZvZ_-9tEfYD2gQe7hTGsgUpiiBSXI8/edit#gid=0

### KoNLTK: Korean Natural Language ToolKit
- KoNLPy(“코엔엘파이”라고 읽습니다)는 한국어 정보처리를 위한 파이썬 패키지
- tokenizing

In [62]:
news_title = str(new_news_summary["news_title"][0])
news_article = str(new_news_summary["news_article"][0])
print('title:',news_title,'\narticle:',news_article)

title: 러시아 고양이는 안 됩니다 
article: 전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다


In [63]:
type(news_title)

str

### Mecab 형태소 분석기
- 일본어용 형태소 분석기를 한국어를 사용할 수 있도록 수정

In [64]:
from konlpy.tag import Mecab 
# from eunjeon import Mecab 
mecab = Mecab()

In [65]:
# 텍스트에서 형태소를 반환한다
print(mecab.morphs(news_title))

['러시아', '고양이', '는', '안', '됩니다']


In [66]:
# 텍스트에서 명사를 반환한다
print(mecab.nouns(news_title))

['러시아', '고양이']


In [67]:
# 텍스트에서 품사 정보를 부착하여 반환한다
print(mecab.pos(news_title))

[('러시아', 'NNP'), ('고양이', 'NNG'), ('는', 'JX'), ('안', 'MAG'), ('됩니다', 'VV+EF')]


---

### Kkma
- 서울대학교 IDS(intelligent Data Systems) 연구실에서 개발

In [68]:
from konlpy.tag import Kkma 
JVM_PATH = '/Library/Java/JavaVirtualMachines/zulu-15.jdk/Contents/Home/bin/java'
kkma = Kkma(jvmpath=JVM_PATH)

[0.007s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016b350000-0x000000016b35c000).
[0.007s][warning][os,thread] Attempt to deallocate stack guard pages failed.


In [69]:
# 텍스트에서 형태소를 반환한다
print(kkma.morphs(news_title))

['러시아', '고양이', '는', '안', '되', 'ㅂ니다']


In [70]:
# 텍스트에서 명사를 반환한다
print(kkma.nouns(news_title))

['러시아', '고양이']


In [71]:
# 텍스트에서 품사 정보를 부착하여 반환한다
print(kkma.pos(news_title))

[('러시아', 'NNG'), ('고양이', 'NNG'), ('는', 'JX'), ('안', 'MAG'), ('되', 'VV'), ('ㅂ니다', 'EFN')]


---

### Okt (Twitter)
- 오픈 소스 한국어 분석기이고, 과거 트위터 형태소 분석기

In [72]:
# from konlpy.tag import Twitter
from konlpy.tag import Okt  
okt = Okt(jvmpath=JVM_PATH) 

In [73]:
# 텍스트에서 형태소를 반환한다
print(okt.morphs(news_title))

['러시아', '고양이', '는', '안', '됩니다']


In [74]:
# 텍스트에서 명사를 반환한다
print(okt.nouns(news_title))

['러시아', '고양이', '안']


In [75]:
# 텍스트에서 어절을 뽑아낸다
print(okt.phrases(news_title))

['러시아', '러시아 고양이', '고양이']


In [76]:
# 텍스트에서 품사 정보를 부착하여 반환한다
print(okt.pos(news_title))

[('러시아', 'Noun'), ('고양이', 'Noun'), ('는', 'Josa'), ('안', 'Noun'), ('됩니다', 'Verb')]


---

## 6. News Article 유사도 분석
- title과 article의 유사도 분석하기

In [77]:
idx_groups = new_news_summary.groupby('news_idx')
idx_groups.size()
#pandas.core.groupby.generic.DataFrameGroupBy
# type(idx_groups)
# idx_groups.sort_values(by='news_idx' ,ascending=True)

news_idx
1        7
2        8
3        9
4        7
5       12
        ..
1534    20
1535    11
1536    28
1537    11
1538    37
Length: 1538, dtype: int64

In [78]:
# 딕셔너리로 범주별로 저장
group_news_df = dict(list(idx_groups))
# pandas.core.frame.DataFrame
# type(group_news_df[1])
group_news_df[1][:2]

news_idx      news_title          news_subtitle  \
0         1  러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
1         1  러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   

                            news_article  
0    전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다  
1  이에 러시아 고양이도 국제 대회에 출전하지 못한다는 소식이 전해졌다

In [79]:
#==위와동일
new_news_summary[new_news_summary['news_idx']==1][:2]

news_idx      news_title          news_subtitle  \
0         1  러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   
1         1  러시아 고양이는 안 됩니다  국제고양이연맹, '월드 캣 쇼'서 퇴출   

                            news_article  
0    전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다  
1  이에 러시아 고양이도 국제 대회에 출전하지 못한다는 소식이 전해졌다

In [80]:
len(new_news_summary.index)

28992

In [81]:
%%time
#pandas apply()
total_news_title = []
total_news_article = []
for i in range(len(new_news_summary.index)) :
    news_title = new_news_summary[new_news_summary['news_idx']==i+1].news_title
    news_article = new_news_summary[new_news_summary['news_idx']==i+1].news_article
    total_news_title.append(news_title)
    total_news_article.append(news_article)

CPU times: user 16.9 s, sys: 120 ms, total: 17 s
Wall time: 8.41 s


In [82]:
print(total_news_title[0])

0    러시아 고양이는 안 됩니다
1    러시아 고양이는 안 됩니다
2    러시아 고양이는 안 됩니다
3    러시아 고양이는 안 됩니다
4    러시아 고양이는 안 됩니다
5    러시아 고양이는 안 됩니다
6    러시아 고양이는 안 됩니다
Name: news_title, dtype: object


In [83]:
print(total_news_article[0])

0                  전 세계가 우크라이나를 침공한 러시아에 각종 제재를 가하고 있다
1                이에 러시아 고양이도 국제 대회에 출전하지 못한다는 소식이 전해졌다
2    지난 3일현지 시각 영국 일간 데일리메일에 따르면 70여 년 역를 가 국제고양이연맹...
3    고양이연맹은 예쁜 고양이 대회를 비롯해 매년 700여 개의 고양이 관련 대회를 주최해왔다
4    연맹 측은 오는 5월 말까지 러시아산 고양이의 수입을 금지하고 러시아에서 태어난 고...
5        이어 우크라이나 난민과 피란 중인 반려동물을 위한 기금도 마련할 것이라고 덧붙였다
6                  러시아 고양이의 국제 대회 출전 금지령에 대해 어떻게 생각하나요
Name: news_article, dtype: object


---

### Mecab 형태소 분석

- news_article

In [84]:
%%time
# total_news_title
# total_news_article
total_group_news_article = []
for group_news_article in total_news_article :
    
    news_article_sentence = []
    for sentence in group_news_article:
        news_noun = ' '.join(mecab.nouns(sentence))
        news_article_sentence.append(news_noun)
    total_group_news_article.append(news_article_sentence)

CPU times: user 2.12 s, sys: 29.8 ms, total: 2.15 s
Wall time: 1.63 s


In [85]:
total_group_news_article[0]

['세계 우크라이나 침공 러시아 각종 제재',
 '이 러시아 고양이 국제 대회 출전 소식',
 '일 현지 시각 영국 일간 데일리 메일 년 역 국제 고양이 연맹 최근 성명 월드 캣 쇼 러시아 소속 고양이 참가 금지',
 '고양이 연맹 고양이 대회 개 고양이 관련 대회 주최',
 '연맹 측 월 말 러시아 고양이 수입 금지 러시아 고양이 혈통서 등록 허용 우크라이나 러시아 잔혹 행위 이상 침묵 수',
 '우크라 난민 피란 중 반려 동물 기금 마련 것',
 '러시아 고양이 국제 대회 출전 금지령 생각']

- news_title

In [86]:
%%time
# total_news_title
# total_news_article
total_group_news_title = []
for group_news_title in total_news_title :
    
    news_title_sentence = []
    for sentence in group_news_title:
        news_noun = ' '.join(mecab.nouns(sentence))
        news_title_sentence.append(news_noun)
    total_group_news_title.append(news_title_sentence)

CPU times: user 582 ms, sys: 5.2 ms, total: 587 ms
Wall time: 589 ms


In [87]:
total_group_news_title[0]

['러시아 고양이', '러시아 고양이', '러시아 고양이', '러시아 고양이', '러시아 고양이', '러시아 고양이', '러시아 고양이']

---

In [88]:
import pprint
pp = pprint.PrettyPrinter(indent=0,width=170,compact=False)

### 사이킷런을 이용한 DTM, TF-IDF, 코사인 유사도
- 텍스트를 수치화


In [89]:
len(total_group_news_title)

28992

In [90]:
%%time
total_corpus = []
for i in range(len(total_group_news_title)):
    corpus = []
    # print(total_group_news_title[1])
    # print(total_group_news_article[1])
    # print(len(total_group_news_title[1]))
    for j in range(len(total_group_news_title[i])):
        corpus_group = []
        corpus_group.append(total_group_news_title[i][j])
        corpus_group.append(total_group_news_article[i][j])
        corpus.append(corpus_group)
    total_corpus.append(corpus)

CPU times: user 1.7 s, sys: 16.3 ms, total: 1.72 s
Wall time: 327 ms


In [91]:
len(total_corpus[0][0])

2

In [92]:
pp.pprint(total_corpus[0])
type(total_corpus[0])

[['러시아 고양이', '세계 우크라이나 침공 러시아 각종 제재'],
['러시아 고양이', '이 러시아 고양이 국제 대회 출전 소식'],
['러시아 고양이', '일 현지 시각 영국 일간 데일리 메일 년 역 국제 고양이 연맹 최근 성명 월드 캣 쇼 러시아 소속 고양이 참가 금지'],
['러시아 고양이', '고양이 연맹 고양이 대회 개 고양이 관련 대회 주최'],
['러시아 고양이', '연맹 측 월 말 러시아 고양이 수입 금지 러시아 고양이 혈통서 등록 허용 우크라이나 러시아 잔혹 행위 이상 침묵 수'],
['러시아 고양이', '우크라 난민 피란 중 반려 동물 기금 마련 것'],
['러시아 고양이', '러시아 고양이 국제 대회 출전 금지령 생각']]


list

In [93]:
len(total_corpus[0])

7

In [94]:
pp.pprint(total_corpus[0][0])

['러시아 고양이', '세계 우크라이나 침공 러시아 각종 제재']


#### 문서 단어 행렬(Document-Term Matrix, DTM)
- 다수의 문서에서 등장하는 각 단어들의 빈도를 행렬로 표현

In [95]:
%%time
from sklearn.feature_extraction.text import CountVectorizer

total_news_dtms = []
total_news_dtms_vocabulary = []
for i in range(len(total_corpus[0])):
    news_dtms = []
    news_dtms_vocabulary = []
    # 코퍼스로부터 각 단어의 빈도수를 기록
    for c in total_corpus[i] :
        # Counter Vectorizer 객체 생성
        vector = CountVectorizer()
        news_dtm = vector.fit_transform(c).toarray()
        news_dtms.append(news_dtm)
        news_dtms_vocabulary.append(sorted(vector.vocabulary_))
    total_news_dtms.append(news_dtms)
    total_news_dtms_vocabulary.append(news_dtms_vocabulary)

CPU times: user 19.8 ms, sys: 3.8 ms, total: 23.6 ms
Wall time: 24.6 ms


In [96]:
pp.pprint(total_news_dtms[0])
pp.pprint(total_news_dtms_vocabulary[0])

[array([[0, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 1]]),
array([[1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1]]),
array([[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
array([[1, 0, 0, 1, 0, 0],
       [3, 1, 2, 0, 1, 1]]),
array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
array([[1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 1]]),
array([[1, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1]])]
[['각종', '고양이', '러시아', '세계', '우크라이나', '제재', '침공'],
['고양이', '국제', '대회', '러시아', '소식', '출전'],
['고양이', '국제', '금지', '데일리', '러시아', '메일', '성명', '소속', '시각', '연맹', '영국', '월드', '일간', '참가', '최근', '현지'],
['고양이', '관련', '대회', '러시아', '연맹', '주최'],
['고양이', '금지', '등록', '러시아', '수입', '연맹', '우크라이나', '이상', '잔혹', '침묵', '행위', '허용', '혈통서'],
['고양이', '기금', '난민', '동물', '러시아', '마련', '반려', '우크라', '피란'],
['고양이', '국제', '금지령', '대회', '러시아', '생각', '출전']]


#### TF-IDF

In [97]:
# 위의 Data Frame 형태의 유사도를 계산
from sklearn.feature_extraction.text import TfidfVectorizer

# tfidf = TfidfVectorizer(stop_words='english')
tfidf = TfidfVectorizer()
news_tfidf_matrix = []
news_tfidf_vocabulary = []

for t in corpus :
    tfidf_matrix = tfidf.fit_transform(t).toarray() # <class 'numpy.ndarray'>
    news_tfidf_matrix.append(tfidf_matrix)
    print('TF-IDF 행렬의 크기(shape) :',tfidf_matrix.shape)
    news_tfidf_vocabulary.append(sorted(tfidf.vocabulary_))
    
pp.pprint(news_tfidf_matrix)
pp.pprint(news_tfidf_vocabulary)

[]
[]


#### DataFrame 형태로 변경

- DTM to DataFrame

In [98]:
countvect_df = pd.DataFrame(total_news_dtms[0][0],columns = total_news_dtms_vocabulary[0][0])
countvect_df.index = ['text1', 'text2']
countvect_df

각종  고양이  러시아  세계  우크라이나  제재  침공
text1   0    1    1   0      0   0   0
text2   1    0    1   1      1   1   1

In [99]:
# pp.pprint(total_news_dtms[1])
# pp.pprint(total_news_dtms_vocabulary[1])
total_dfs = []
for i in range(len(total_news_dtms[0])):
    dfs = []
    for news_dtm in total_news_dtms[i] :
        countvect_df = pd.DataFrame(news_dtm)
        dfs.append(countvect_df)
    total_dfs.append(dfs)

In [100]:
total_dfs[0][0]

0  1  2  3  4  5  6
0  0  1  1  0  0  0  0
1  1  0  1  1  1  1  1

In [101]:
len(total_dfs[0])

7

#### 코사인 유사도
- 자카드 유사도

- sklearn

In [102]:
from sklearn.metrics.pairwise import cosine_similarity
total_group_cosine_sim = []

for i in range(len(total_dfs)):
    total_cosine_sim = []
    for i in range(len(total_dfs[0])) :
        cosine_sim = cosine_similarity(total_dfs[0][i], total_dfs[0][i])
        total_cosine_sim.append(cosine_sim)
    total_group_cosine_sim.append(total_cosine_sim)
pp.pprint(total_group_cosine_sim[0])

[array([[1.        , 0.28867513],
       [0.28867513, 1.        ]]),
array([[1.        , 0.57735027],
       [0.57735027, 1.        ]]),
array([[1.        , 0.48666426],
       [0.48666426, 1.        ]]),
array([[1.        , 0.53033009],
       [0.53033009, 1.        ]]),
array([[1.        , 0.72168784],
       [0.72168784, 1.        ]]),
array([[1., 0.],
       [0., 1.]]),
array([[1.        , 0.53452248],
       [0.53452248, 1.        ]])]


In [103]:
pp.pprint(total_group_cosine_sim[0][0])

array([[1.        , 0.28867513],
       [0.28867513, 1.        ]])


In [104]:
pp.pprint(total_group_cosine_sim[0][0][0])

array([1.        , 0.28867513])


In [105]:
pp.pprint(total_group_cosine_sim[0][0][0][1])

0.2886751345948129


In [106]:
len(total_group_cosine_sim[0])

7

In [107]:
for i in range(len(total_group_cosine_sim[0])):
    print('Cosine Similarity',total_group_cosine_sim[0][i][0][1])

Cosine Similarity 0.2886751345948129
Cosine Similarity 0.5773502691896258
Cosine Similarity 0.4866642633922875
Cosine Similarity 0.5303300858899106
Cosine Similarity 0.7216878364870323
Cosine Similarity 0.0
Cosine Similarity 0.5345224838248487


In [108]:
# 데이터 확인
pp.pprint(total_corpus[0])

[['러시아 고양이', '세계 우크라이나 침공 러시아 각종 제재'],
['러시아 고양이', '이 러시아 고양이 국제 대회 출전 소식'],
['러시아 고양이', '일 현지 시각 영국 일간 데일리 메일 년 역 국제 고양이 연맹 최근 성명 월드 캣 쇼 러시아 소속 고양이 참가 금지'],
['러시아 고양이', '고양이 연맹 고양이 대회 개 고양이 관련 대회 주최'],
['러시아 고양이', '연맹 측 월 말 러시아 고양이 수입 금지 러시아 고양이 혈통서 등록 허용 우크라이나 러시아 잔혹 행위 이상 침묵 수'],
['러시아 고양이', '우크라 난민 피란 중 반려 동물 기금 마련 것'],
['러시아 고양이', '러시아 고양이 국제 대회 출전 금지령 생각']]


In [109]:
# for i, sim in enumerate(total_group_cosine_sim[0]):
#     print(sim)

---

#### 질문!!!
- dtm, tf-idf가 정수인코딩의 한 종류/ 사이킷런 사용 해라!
    - NLTK의 FreqDist?, 케라스(Keras)? 어떤걸 사용해야하는지?
    - 알고리즘의 일치 여부 체크해야 함 (주제어)
    - tf-idf 하나의 array
    
- 원핫인코딩 진행 후 -> 코싸인 유사도?? -> 사용 하지 마라(도드라진 문장/ 독특한 문장) 이니까!! 별로다


- 패딩 진행 후 ->코싸인 유사도??
    - tf-idf는 패딩 안해도 됨!
    - 모델 만들 때만 수행!
- 전처리 과정을 모두 수행 해야하는지, 궁금!!

---

### 케라스(Keras)를 이용한 원-핫 인코딩(One-Hot Encoding)

- 케라스 토크나이저를 이용한 정수 인코딩

In [118]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer(num_words=1000)

for v in news_article_sentence:
    # 가장 빈도가 높은 1,000개의 단어만 선택하도록하는 Tokenizer 객체
    tokenizer = Tokenizer(num_words=1000)
    tokenizer.fit_on_texts([v])
    news_article_dic = tokenizer.word_index
    print(news_article_dic)

In [119]:
tokenizer

In [120]:
# 문자열을 인덱스의 리스트로 변환
# article
for v in news_article_sentence:
    article_sequences = tokenizer.texts_to_sequences([v])
    # print(one_hot_results)
    pp.pprint(article_sequences)

In [121]:
# title
title_sequences = tokenizer.texts_to_sequences(news_title_sentence)
print(news_title_sentence)
print(title_sequences)

[]
[]


- 정수 인코딩 된 결과로부터 원-핫 인코딩을 수행

In [122]:
one_hot_title = to_categorical(title_sequences)
print(one_hot_title)

ValueError: zero-size array to reduction operation maximum which has no identity

In [123]:
one_hot_article = to_categorical(article_sequences[0])
print(one_hot_article)

NameError: name 'article_sequences' is not defined